name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: archlinux-latest
    steps:    
    - name: Install GCC
      run: sudo pacman -S gcc
    - name: Install Nasm
      run: sudo pacman -S nas
    - uses: actions/checkout@v4
    - name: make all
      run: make all
