name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:    
    - name: Install GCC
      run: sudo apt-get install -y g++
    - uses: actions/checkout@v4
    - name: make all
      run: make all
